### ISSUE TITLE
cannot search for function by name

### ISSUE THREAD

**Issue by davidchambers** [kedashoe/hindley-milner-search#4]
Should this work?

```javascript
'use strict';

const HMS = require('./src/hm-search.js');

const db = HMS.index([
  'foo :: Int -> String',
  'bar :: Int -> Int',
  'blam :: Int -> Maybe Int',
]);

HMS.search(db, 'foo');
```

A type error is thrown when we attempt to read the `'name'` property of `undefined` on [line 140][1].

[1]: https://github.com/kedashoe/hindley-milner-search/blob/v0.1.2/src/hm-search.js#L140

**Comment by kedashoe** [comment]
Thanks for issue, yes, that should not be dying. It is throwing when it tries to parse your search term "foo". Error is because of https://github.com/kedashoe/hindley-milner-parser-js/commit/ac3dbea72778ed100b8469172a55966b7ff12b81, and how nearley handles failed parses vs mona. I'm going to fix this in HMP. Should be able to get to it today at some point.

**Comment by kedashoe** [comment]
```bash
$ grep search package.json 
    "hindley-milner-search": "^0.1.3"
$ cat index.js 
'use strict';

const HMS = require('hindley-milner-search');

const db = HMS.index([
  'foo :: Int -> String',
  'bar :: Int -> Int',
  'blam :: Int -> Maybe Int',
]);

console.log(HMS.search(db, 'foo'));

$ node index.js 
[ { name: 'foo',
    constraints: [],
    type: { type: 'function', text: '', children: [Object] },
    signature: 'foo :: Int -> String',
    pointer: 0 } ]
```
ok, I think if you bump hindley-milner-search version to 0.1.3 you should be back in business
